FROM php:7.4-fpm


RUN apt-get update

COPY ./fpm/wait-for-it.sh /usr/bin/wait-for-it

RUN chmod +x /usr/bin/wait-for-it

RUN apt-get install -y libssl-dev zlib1g-dev curl git unzip netcat libxml2-dev libpq-dev libzip-dev \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql pgsql

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
ADD composer.json composer.lock /var/www/api.jettour.live/

WORKDIR /var/www/api.jettour.live/
RUN composer install --no-scripts --no-autoloader && \
    composer clear-cache


CMD wait-for-it database:5432 -- ./bin/console doctrine:migrations:migrate; php-fpm



