#index:
#    path: /
#    controller: App\Controller\DefaultController::index

get_tours:
  path: /tours
  controller: App\Controller\TourController::getTours
  methods: GET

get_tour:
  path: /tours/{id}
  controller: App\Controller\TourController::getTour
  methods: GET

get_routes:
  path: /tours/{tour_id}/route
  controller: App\Controller\RouteController::getRoute
  methods: GET