#index:
#    path: /
#    controller: App\Controller\DefaultController::index

get_tours:
  path: /tours
  controller: App\Controller\TourController::getTours
  methods: GET

get_tour:
  path: /tour/{id}
  controller: App\Controller\TourController::getTour
  methods: GET
